[project-desk]
user = project-desk
group = project-desk

listen = /run/php/project-desk.sock
listen.owner = project-desk
listen.group = www-data
listen.mode = 0660

pm = dynamic
pm.max_children = 10
pm.start_servers = 2
pm.min_spare_servers = 2
pm.max_spare_servers = 5
pm.max_requests = 500

clear_env = no
catch_workers_output = yes
decorate_workers_output = no
security.limit_extensions = .php

php_admin_flag[display_errors] = off
php_admin_value[error_log] = /var/www/project-desk/storage/logs/php-fpm.log
php_admin_value[session.cookie_secure] = 1
php_admin_value[session.cookie_httponly] = 1
php_admin_value[session.cookie_samesite] = Lax
